### ISSUE TITLE
Call for Participants

### ISSUE THREAD

**Issue by chrisdickinson** [dylibso/wasi-observe#1]
If you're interested in participating in this proposal, please raise your hand here! Please state your desired level of commitment and interest in the project, too – e.g.:

> Hi, I'm Chris, working at Dylibso, Inc. I intend to act as a champion for this proposal on behalf of Dylibso – so I'll be available for regular (weekly or fortnightly) meetings, as well as specification and implementation work. I'm based out of the US/Pacific timezone.

or

> Hi, I'm Alex, working at An Example O11Y Vendor. I intend to act as a interested party; so I'll be available for some meetings and to give feedback on specification changes. I'm based out of the America/Central timezone.

(Unless someone requests that we extend this call, I intend to leave this issue open until Jan 12th.)

**Comment by nilslice** [comment]
tagging @squillace as requested!

**Comment by endocrimes** [comment]
Hi, I'm Danielle - I work at Fermyon. I intend to help initially drive this on behalf of Fermyon and my own interest. I'll be available for regular (weekly or fortnightly) meetings, as well as specification and implementation work. I live in Berlin (CET) but work on a ~UTC-2 schedule.

**Comment by Walther** [comment]
Hi, I'm Veeti aka Walther and currently unaffiliated. This sounds like an interesting project and I would love to learn more and try to help with the work where I can. I should be able to commit to a couple of days a month or so for this project, at least for now. I live in Helsinki (UTC+2) but I'm used to a later working schedule, so attending occasional meetings in the morning Pacific time / evening local time should be perfectly fine.

**Comment by brooksmtownsend** [comment]
Hey folks, I'm Brooks and I work at Cosmonic in addition to being a maintainer of https://github.com/wasmCloud/wasmCloud for the past 4 years. We have some OTEL instrumentation in wasmCloud and I'd like to help drive this in the interest of the open source application use case. I work in the US Eastern time zone.

**Comment by chrisdickinson** [comment]
Hi folks! Thanks for your interest! The next steps are:

1. I'll reach out soon to schedule a meeting in the coming week to go over the design values and goals; there's a rough draft [in the README.md](https://github.com/dylibso/wasi-observe#introduction) if you want to check that out – feel free to propose edits via PR ahead of the meeting, too!
2. We're on the [WASI meeting schedule](https://github.com/WebAssembly/meetings/blob/main/wasi/2024/WASI-02-08.md#agenda-items) for a phase 1 vote on Feb 8th.
    - _(This is my first time going through the WASI proposal myself! I intend to reach out to some folks who have worked on WASI proposals before to get an idea of what to expect so we can talk about it at our meeting.)_
    - As a heads up, if you want to attend the WASI meeting, you'll have to sign up for the [W3C WebAssembly Community Group](https://www.w3.org/community/webassembly/).

Thanks for raising your hands for this – I look forward to working with you all! I'm going to close this issue now.

(If other folks happen upon this issue later and are interested in participating I encourage them to comment here! I've put a deadline on this issue for scheduling purposes more than anything else :smile: I'll repeat this message in an edit of the original issue text.)
